### ISSUE TITLE
docker-php-ext-install readline fails on 7.4.23

### ISSUE THREAD

**Issue by wiseelf** [docker-library/php#1197]
Steps to reproduce:
1. Take clean php:7.4-apache image
2. apt update && apt install libedit-dev
3. docker-php-ext-install readline
```
creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
/bin/bash /usr/src/php/ext/readline/libtool --mode=compile cc  -I. -I/usr/src/php/ext/readline -DPHP_ATOM_INC -I/usr/src/php/ext/readline/include -I/usr/src/php/ext/readline/main -I/usr/src/php/ext/readline -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/editline  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -c /usr/src/php/ext/readline/readline.c -o readline.lo
mkdir .libs
 cc -I. -I/usr/src/php/ext/readline -DPHP_ATOM_INC -I/usr/src/php/ext/readline/include -I/usr/src/php/ext/readline/main -I/usr/src/php/ext/readline -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/editline -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c /usr/src/php/ext/readline/readline.c  -fPIC -DPIC -o .libs/readline.o
In file included from /usr/local/include/php/main/php.h:37,
                 from /usr/src/php/ext/readline/readline.c:25:
/usr/src/php/ext/readline/readline.c: In function 'zif_readline_info':
/usr/src/php/ext/readline/readline.c:258:38: error: 'rl_mark' undeclared (first use in this function)
  258 |   add_assoc_long(return_value,"mark",rl_mark);
      |                                      ^~~~~~~
/usr/local/include/php/Zend/zend_API.h:402:90: note: in definition of macro 'add_assoc_long'
  402 | #define add_assoc_long(__arg, __key, __n) add_assoc_long_ex(__arg, __key, strlen(__key), __n)
      |                                                                                          ^~~
/usr/src/php/ext/readline/readline.c:258:38: note: each undeclared identifier is reported only once for each function it appears in
  258 |   add_assoc_long(return_value,"mark",rl_mark);
      |                                      ^~~~~~~
/usr/local/include/php/Zend/zend_API.h:402:90: note: in definition of macro 'add_assoc_long'
  402 | #define add_assoc_long(__arg, __key, __n) add_assoc_long_ex(__arg, __key, strlen(__key), __n)
      |                                                                                          ^~~
/usr/src/php/ext/readline/readline.c:260:47: error: 'rl_pending_input' undeclared (first use in this function)
  260 |   add_assoc_long(return_value,"pending_input",rl_pending_input);
      |                                               ^~~~~~~~~~~~~~~~
/usr/local/include/php/Zend/zend_API.h:402:90: note: in definition of macro 'add_assoc_long'
  402 | #define add_assoc_long(__arg, __key, __n) add_assoc_long_ex(__arg, __key, strlen(__key), __n)
      |                                                                                          ^~~
/usr/src/php/ext/readline/readline.c:267:60: error: 'rl_completion_suppress_append' undeclared (first use in this function)
  267 |   add_assoc_bool(return_value,"completion_suppress_append",rl_completion_suppress_append);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/php/Zend/zend_API.h:404:90: note: in definition of macro 'add_assoc_bool'
  404 | #define add_assoc_bool(__arg, __key, __b) add_assoc_bool_ex(__arg, __key, strlen(__key), __b)
      |                                                                                          ^~~
make: *** [Makefile:192: readline.lo] Error 1
```

On 7.4.22 works well.

**Comment by fhsinchy** [comment]
Having the same issue. Works fine on 7.4.22

**Comment by wglambert** [comment]
Hmm, I thought it might've been related to Bullseye specifically but `php:7.4.23-buster` runs into the same error. 

<details>
<summary> docker build php:7.4.23-buster </summary>

```console
$ docker build -t php:test - << EOF
FROM php:7.4.23-buster
RUN apt update && apt install -y libedit-dev && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install readline
EOF
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM php:7.4.23-buster
 ---> fcb027c41b81
Step 2/3 : RUN apt update && apt install -y libedit-dev && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> a6883e8fa436
Step 3/3 : RUN docker-php-ext-install readline
 ---> Running in 0e0898accb12
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20190902
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for libedit readline replacement... yes, shared
checking for libedit... yes
checking for tgetent in -lncurses... yes
checking for readline in -ledit... yes
checking for rl_callback_read_char in -ledit... yes
checking for rl_on_new_line in -ledit... yes
checking for rl_completion_matches in -ledit... yes
checking for history_list in -ledit... yes
checking for a sed that does not truncate output... /bin/sed
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
/bin/bash /usr/src/php/ext/readline/libtool --mode=compile cc  -I. -I/usr/src/php/ext/readline -DPHP_ATOM_INC -I/usr/src/php/ext/readline/include -I/usr/src/php/ext/readline/main -I/usr/src/php/ext/readline -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/editline  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -c /usr/src/php/ext/readline/readline.c -o readline.lo 
mkdir .libs
 cc -I. -I/usr/src/php/ext/readline -DPHP_ATOM_INC -I/usr/src/php/ext/readline/include -I/usr/src/php/ext/readline/main -I/usr/src/php/ext/readline -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/editline -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c /usr/src/php/ext/readline/readline.c  -fPIC -DPIC -o .libs/readline.o
In file included from /usr/local/include/php/main/php.h:37,
                 from /usr/src/php/ext/readline/readline.c:25:
/usr/src/php/ext/readline/readline.c: In function 'zif_readline_info':
/usr/src/php/ext/readline/readline.c:258:38: error: 'rl_mark' undeclared (first use in this function); did you mean 'fd_mask'?
   add_assoc_long(return_value,"mark",rl_mark);
                                      ^~~~~~~
/usr/local/include/php/Zend/zend_API.h:402:90: note: in definition of macro 'add_assoc_long'
 #define add_assoc_long(__arg, __key, __n) add_assoc_long_ex(__arg, __key, strlen(__key), __n)
                                                                                          ^~~
/usr/src/php/ext/readline/readline.c:258:38: note: each undeclared identifier is reported only once for each function it appears in
   add_assoc_long(return_value,"mark",rl_mark);
                                      ^~~~~~~
/usr/local/include/php/Zend/zend_API.h:402:90: note: in definition of macro 'add_assoc_long'
 #define add_assoc_long(__arg, __key, __n) add_assoc_long_ex(__arg, __key, strlen(__key), __n)
                                                                                          ^~~
/usr/src/php/ext/readline/readline.c:260:47: error: 'rl_pending_input' undeclared (first use in this function); did you mean 'rl_readline_name'?
   add_assoc_long(return_value,"pending_input",rl_pending_input);
                                               ^~~~~~~~~~~~~~~~
/usr/local/include/php/Zend/zend_API.h:402:90: note: in definition of macro 'add_assoc_long'
 #define add_assoc_long(__arg, __key, __n) add_assoc_long_ex(__arg, __key, strlen(__key), __n)
                                                                                          ^~~
/usr/src/php/ext/readline/readline.c:267:60: error: 'rl_completion_suppress_append' undeclared (first use in this function); did you mean 'rl_completion_query_items'?
   add_assoc_bool(return_value,"completion_suppress_append",rl_completion_suppress_append);
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/php/Zend/zend_API.h:404:90: note: in definition of macro 'add_assoc_bool'
 #define add_assoc_bool(__arg, __key, __b) add_assoc_bool_ex(__arg, __key, strlen(__key), __b)
                                                                                          ^~~
make: *** [Makefile:192: readline.lo] Error 1
The command '/bin/sh -c docker-php-ext-install readline' returned a non-zero code: 2
```

</details>

And with 7.4.22-buster
```console
$ docker build -t php:test - << EOF
FROM php:7.4.22-buster
RUN apt update && apt install -y libedit-dev && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install readline
EOF
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM php:7.4.22-buster
 ---> abd02f2f4f18
Step 2/3 : RUN apt update && apt install -y libedit-dev && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> b55ee7275816
Step 3/3 : RUN docker-php-ext-install readline
 ---> Using cache
 ---> dd795a3babd8
Successfully built dd795a3babd8
Successfully tagged php:test
```

Can't find anything relevant on `error: 'rl_mark' undeclared` with readline

**Comment by tianon** [comment]
I think the readline module is built-in because it's required for `php -a` to have interactive line editing.

**Comment by wglambert** [comment]
Ah so it is
```console
$ docker run --rm php:7.4.23-bullseye php -i | grep readline
Configure Command =>  './configure'  '--build=x86_64-linux-gnu' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-openssl' '--with-readline' '--with-zlib' '--with-pear' '--with-libdir=lib/x86_64-linux-gnu' '--enable-embed' 'build_alias=x86_64-linux-gnu'
readline
```

https://github.com/docker-library/docs/tree/master/php#default-extensions

Closing since this is resolved
